global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker_servers'
    static_configs:
      - targets: 
        - 'deployingreliable.software:9323'
        - 'deployingreliable.software:9100'
        - 'monitor.deployingreliable.software:9323'
        - 'monitor.deployingreliable.software:9100'
