development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis_service
  url: <%= ENV.fetch("REDIS_URL") { "redis_service://localhost:6379/1" } %>
  channel_prefix: backend_production
