version: '3.7'
services:
  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
    - ./backend:/app
    - gems:/usr/local/bundle
    depends_on:
      - db
    ports:
      - 3000:80
    command: bash -c "
      rm -f /app/tmp/pids/server.pid
      && bundle i
      && rails s -b 0.0.0.0 -p 80"
  frontend:
    build:
      context: ./blog-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./blog-frontend:/app
      - node_modules:/app/node_modules
    ports:
      - 4200:80
  db:
    image: postgres:12
    volumes:
      - /var/lib/postgresql/data
      - ./config/db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: blog
      POSTGRES_PASSWORD: blog
      POSTGRES_USER: blog
volumes:
  gems:
  node_modules:
