# override parts of default docker-compose.yml
version: '3.7'
services:
  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - 3000:80
    command: bash -c "
      rm -f /app/tmp/pids/server.pid
      && bundle i
      && rails s -b 0.0.0.0 -p 80"
  # backend:
  #   image: liujordan/reliable-blog:backend-1.0.0
  #   ports:
  #     - 3000:3000
  #   environment:
  #     SECRET_KEY_BASE: 5a37811464e7d378488b0f073e2193b093682e4e21f5d6f3ae0a4e1781e61a351fdc878a843424e81c73fb484a40d23f92c8dafac4870e74ede6e5e174423010
  #     VIRTUAL_HOST: backend.localhost
  frontend:
    build:
      context: ./blog-frontend
      dockerfile: dev.Dockerfile
    ports:
      - 4200:80
  # frontend:
  #   image: liujordan/reliable-blog:frontend-1.0.0
  #   ports:
  #     - 4200:80
  db:
    ports: 
      - 5423:5432

