version: '3.0'
services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    ports:
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all"]

      