---
- name: Install EPEL repo
  yum:
    name: epel-release
    state: present
  become: yes
  when : "'epel-release' not in ansible_facts.packages"
- name: Install Pip
  yum:
    name: python-pip
    state: present
  become: yes
  when : "'python2-pip' not in ansible_facts.packages"

