---
- name: Get the rpm package facts
  package_facts:
    manager: rpm
- name: "Running OS specific tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
