MONGO_QUERYSTORE_URL: 'mongodb://querystore/myproject'
MONGO_QUERYMAP_URL: 'mongodb://clickmap/myproject'
REDIS_HOST: 'clicklog'

SENTRY_DSN: 'https://da3b7d51a9b949ee8ed047304e110b35:0b3b79998f104f22846de894e884aa86@sentry.io/1884988'
