---
- name: Create Docker folders
  file:
    path: "{{ root_directory }}"
    owner: root
    group: docker
    state: directory
    mode: 0755
- name: Copy compose file
  template:
    src: ./templates/docker-compose.nginx.yml.j2
    dest: "{{ root_directory }}/docker-compose.nginx.yml"
  become: yes
- name: Copy configs
  copy:
    src: ./files/config/
    dest: "{{ config_directory }}"
  become: yes
- name: Pull latest images
  command: docker-compose -f "{{ root_directory }}/docker-compose.nginx.yml" pull
- name: Take down compose
  command: docker-compose -f "{{ root_directory }}/docker-compose.nginx.yml" down
- name: Run Compose for Docker nginx
  command: docker-compose -f "{{ root_directory }}/docker-compose.nginx.yml" up -d
