---
- name: Copy compose file
  template:
    src: ./templates/docker-compose.elastic.yml.j2
    dest: "{{ root_directory }}/docker-compose.elastic.yml"
  become: yes
- name: Copy configs
  copy:
    src: ./files/config
    dest: "{{ config_directory }}"
  become: yes
- name: Pull latest images
  command: docker-compose -f "{{ root_directory }}/docker-compose.elastic.yml" pull
- name: Take down compose
  command: docker-compose -f "{{ root_directory }}/docker-compose.elastic.yml" down
- name: Run Compose for Docker nginx
  command: docker-compose -f "{{ root_directory }}/docker-compose.elastic.yml" up -d
