---
- name: Copy compose file
  template:
    src: ./files/docker-compose.prod.yml.j2
    dest: /opt/reliable/docker/docker-compose.yml
  become: yes
- name: Copy configs
  copy:
    src: ./roles/shared-files/config
    dest: /opt/reliable/docker
  become: yes
- name: Login to Github Registries
  docker_login:
    registry: "{{ docker.registry }}"
    username: "{{ docker.username }}"
    password: "{{ docker.password }}"
# TODO Add certs to host and use docker_compose instead of shell command
- name: Run compose
  shell:
    chdir: /opt/reliable/docker
    cmd: docker-compose up -d && docker-compose exec backend rake db:migrate
