---
- name: Create Docker folders
  file:
    path: "{{ root_directory }}"
    owner: root
    group: docker
    state: directory
    mode: 0755
- name: Copy compose file
  template:
    src: ./files/docker-compose.prod.yml.j2
    dest: "{{ root_directory }}/docker-compose.yml"
  become: yes
- name: Copy configs
  copy:
    src: ./files/config/
    dest: "{{ config_directory }}"
  become: yes
- name: Login to Github Registries
  docker_login:
    registry: "{{ docker.registry }}"
    username: "{{ docker.username }}"
    password: "{{ docker.password }}"
- name: Pull latest images
  command: docker-compose -f "{{ root_directory }}/docker-compose.yml" pull
- name: Take down compose
  command: docker-compose -f "{{ root_directory }}/docker-compose.yml" down
- name: Run Compose for reliable blog
  command: docker-compose -f "{{ root_directory }}/docker-compose.yml" up -d
- name: Run migrations
  command: docker-compose -f "{{ root_directory }}/docker-compose.yml" exec backend rails db:migrate
