version: '3.7'
services:
  querystore:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  clickmap:
    image: mongo
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  clicklog:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: clicks
