---
- name: Copy compose file
  template:
    src: ./templates/docker-compose.prometheus.yml.j2
    dest: "{{ root_directory }}/docker-compose.prometheus.yml"
  become: yes
- name: Copy configs
  copy:
    src: ./files/config/
    dest: "{{ config_directory }}"
  become: yes
- name: Pull latest images
  command: docker-compose -f "{{ root_directory }}/docker-compose.prometheus.yml" pull
- name: Take down compose
  command: docker-compose -f "{{ root_directory }}/docker-compose.prometheus.yml" down
- name: Run Compose for Docker nginx
  command: docker-compose -f "{{ root_directory }}/docker-compose.prometheus.yml" up -d
