---
- hosts: deployingreliable.software
  vars:
    - deploy_with_compose: false
  roles:
    - common
    - docker
    - docker-nginx
    - apm-server
    - reliable_blog
    - prometheus
    - elasticsearch
