---
- name: Copy compose file
  template:
    src: docker-compose.kibana.yml.j2
    dest: /opt/reliable/docker/docker-compose.kibana.yml
  become: yes
- name: Copy configs
  copy:
    src: ./roles/shared-files/config
    dest: /opt/reliable/docker
  become: yes
- name: Pull latest images
  command: docker-compose --log-level ERROR -f "{{ root_directory }}/docker-compose.kibana.yml" pull
- name: Deploy services
  command: docker --log-level error stack deploy -c "{{ root_directory }}/docker-compose.kibana.yml" kibana
