name: Publish blog-backend Docker image to GitHub Package Registry
on:
  push:
    branches:
      - master # on push to master
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Copy Repo Files
      uses: actions/checkout@master

     #This Action Emits 2 Variables, IMAGE_SHA_NAME and IMAGE_URL
     #which you can reference in subsequent steps
    - name: Publish Docker Image to GPR
      uses: machine-learning-apps/gpr-docker-publish@master
      id: docker
      with:
        IMAGE_NAME: 'reliable-blog-backend'
        TAG: 'latest'
        DOCKERFILE_PATH: 'backend/Dockerfile'
        BUILD_CONTEXT: 'backend'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy backend
      uses: ./.github/actions/deploy
      env:
        IMAGE_URL: ${{ steps.docker.outputs.IMAGE_SHA_NAME }}
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        VAULT_PASS: ${{ secrets.VAULT_PASS }}
        DEPLOY_FILE: 'redeploy-backend.yml'
